# Generated by Django 4.0.4 on 2022-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=150)),
                ('seller_zip_code_prefix', models.IntegerField()),
                ('seller_city', models.CharField(max_length=150)),
                ('seller_state', models.CharField(max_length=2)),

            ],
        ),
    ]
